// Base de joueurs du Joueur Mystère — saison 2026-27, mise à jour le 2026-08-27
// (mercato d'été 2026 appliqué ; le marché ferme le 01/09 — dossiers ouverts : Watkins, E. Martínez, Barcola, Vlahović, Chiesa)
// Format : [nom, club, championnat, nation, drapeau, confédération, poste G/D/M/A, année de naissance]
window.JM_DATA = /*JM-DATA*/[
["Erling Haaland", "Man City", "Premier League", "Norvège", "🇳🇴", "UEFA", "A", 2000],
["Rodri", "FC Barcelone", "La Liga", "Espagne", "🇪🇸", "UEFA", "M", 1996],
["Phil Foden", "Man City", "Premier League", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "M", 2000],
["Bernardo Silva", "Real Madrid", "La Liga", "Portugal", "🇵🇹", "UEFA", "M", 1994],
["Gianluigi Donnarumma", "Man City", "Premier League", "Italie", "🇮🇹", "UEFA", "G", 1999],
["Joško Gvardiol", "Man City", "Premier League", "Croatie", "🇭🇷", "UEFA", "D", 2002],
["John Stones", "Inter Milan", "Serie A", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "D", 1994],
["Rayan Cherki", "Man City", "Premier League", "France", "🇫🇷", "UEFA", "M", 2003],
["Tijjani Reijnders", "Al-Qadsiah", "Saudi Pro League", "Pays-Bas", "🇳🇱", "UEFA", "M", 1998],
["Omar Marmoush", "Man City", "Premier League", "Égypte", "🇪🇬", "CAF", "A", 1999],
["Jérémy Doku", "Man City", "Premier League", "Belgique", "🇧🇪", "UEFA", "A", 2002],
["Mohamed Salah", "Trabzonspor", "Süper Lig", "Égypte", "🇪🇬", "CAF", "A", 1992],
["Virgil van Dijk", "Liverpool", "Premier League", "Pays-Bas", "🇳🇱", "UEFA", "D", 1991],
["Alisson Becker", "Liverpool", "Premier League", "Brésil", "🇧🇷", "CONMEBOL", "G", 1992],
["Alexis Mac Allister", "Liverpool", "Premier League", "Argentine", "🇦🇷", "CONMEBOL", "M", 1998],
["Dominik Szoboszlai", "Liverpool", "Premier League", "Hongrie", "🇭🇺", "UEFA", "M", 2000],
["Florian Wirtz", "Liverpool", "Premier League", "Allemagne", "🇩🇪", "UEFA", "M", 2003],
["Hugo Ekitiké", "Liverpool", "Premier League", "France", "🇫🇷", "UEFA", "A", 2002],
["Ryan Gravenberch", "Liverpool", "Premier League", "Pays-Bas", "🇳🇱", "UEFA", "M", 2002],
["Ibrahima Konaté", "Real Madrid", "La Liga", "France", "🇫🇷", "UEFA", "D", 1999],
["Alexander Isak", "Liverpool", "Premier League", "Suède", "🇸🇪", "UEFA", "A", 1999],
["Jeremie Frimpong", "Liverpool", "Premier League", "Pays-Bas", "🇳🇱", "UEFA", "D", 2000],
["Federico Chiesa", "Liverpool", "Premier League", "Italie", "🇮🇹", "UEFA", "A", 1997],
["Bukayo Saka", "Arsenal", "Premier League", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "A", 2001],
["Martin Ødegaard", "Arsenal", "Premier League", "Norvège", "🇳🇴", "UEFA", "M", 1998],
["Declan Rice", "Arsenal", "Premier League", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "M", 1999],
["William Saliba", "Arsenal", "Premier League", "France", "🇫🇷", "UEFA", "D", 2001],
["Gabriel Magalhães", "Arsenal", "Premier League", "Brésil", "🇧🇷", "CONMEBOL", "D", 1997],
["David Raya", "Arsenal", "Premier League", "Espagne", "🇪🇸", "UEFA", "G", 1995],
["Viktor Gyökeres", "Arsenal", "Premier League", "Suède", "🇸🇪", "UEFA", "A", 1998],
["Leandro Trossard", "Arsenal", "Premier League", "Belgique", "🇧🇪", "UEFA", "A", 1994],
["Gabriel Martinelli", "Arsenal", "Premier League", "Brésil", "🇧🇷", "CONMEBOL", "A", 2001],
["Kai Havertz", "Arsenal", "Premier League", "Allemagne", "🇩🇪", "UEFA", "A", 1999],
["Martín Zubimendi", "Arsenal", "Premier League", "Espagne", "🇪🇸", "UEFA", "M", 1999],
["Eberechi Eze", "Arsenal", "Premier League", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "M", 1998],
["Cole Palmer", "Chelsea", "Premier League", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "M", 2002],
["Enzo Fernández", "Chelsea", "Premier League", "Argentine", "🇦🇷", "CONMEBOL", "M", 2001],
["Moisés Caicedo", "Chelsea", "Premier League", "Équateur", "🇪🇨", "CONMEBOL", "M", 2001],
["João Pedro", "Chelsea", "Premier League", "Brésil", "🇧🇷", "CONMEBOL", "A", 2001],
["Liam Delap", "Nottingham Forest", "Premier League", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "A", 2003],
["Marc Cucurella", "Real Madrid", "La Liga", "Espagne", "🇪🇸", "UEFA", "D", 1998],
["Levi Colwill", "Chelsea", "Premier League", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "D", 2003],
["Pedro Neto", "Chelsea", "Premier League", "Portugal", "🇵🇹", "UEFA", "A", 2000],
["Estêvão Willian", "Chelsea", "Premier League", "Brésil", "🇧🇷", "CONMEBOL", "A", 2007],
["Alejandro Garnacho", "Chelsea", "Premier League", "Argentine", "🇦🇷", "CONMEBOL", "A", 2004],
["Bruno Fernandes", "Man United", "Premier League", "Portugal", "🇵🇹", "UEFA", "M", 1994],
["Bryan Mbeumo", "Man United", "Premier League", "Cameroun", "🇨🇲", "CAF", "A", 1999],
["Matheus Cunha", "Man United", "Premier League", "Brésil", "🇧🇷", "CONMEBOL", "A", 1999],
["Benjamin Šeško", "Man United", "Premier League", "Slovénie", "🇸🇮", "UEFA", "A", 2003],
["Kobbie Mainoo", "Man United", "Premier League", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "M", 2005],
["Amad Diallo", "Man United", "Premier League", "Côte d'Ivoire", "🇨🇮", "CAF", "A", 2002],
["Senne Lammens", "Man United", "Premier League", "Belgique", "🇧🇪", "UEFA", "G", 2002],
["Bruno Guimarães", "Arsenal", "Premier League", "Brésil", "🇧🇷", "CONMEBOL", "M", 1997],
["Sandro Tonali", "Tottenham", "Premier League", "Italie", "🇮🇹", "UEFA", "M", 2000],
["Anthony Gordon", "FC Barcelone", "La Liga", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "A", 2001],
["Nick Woltemade", "Newcastle", "Premier League", "Allemagne", "🇩🇪", "UEFA", "A", 2002],
["Mohammed Kudus", "Tottenham", "Premier League", "Ghana", "🇬🇭", "CAF", "A", 2000],
["Xavi Simons", "Tottenham", "Premier League", "Pays-Bas", "🇳🇱", "UEFA", "M", 2003],
["Cristian Romero", "Atlético Madrid", "La Liga", "Argentine", "🇦🇷", "CONMEBOL", "D", 1998],
["Guglielmo Vicario", "Tottenham", "Premier League", "Italie", "🇮🇹", "UEFA", "G", 1996],
["Richarlison", "Tottenham", "Premier League", "Brésil", "🇧🇷", "CONMEBOL", "A", 1997],
["James Maddison", "Tottenham", "Premier League", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "M", 1996],
["Jarrod Bowen", "West Ham", "Premier League", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "A", 1996],
["Lucas Paquetá", "West Ham", "Premier League", "Brésil", "🇧🇷", "CONMEBOL", "M", 1997],
["Ollie Watkins", "Aston Villa", "Premier League", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "A", 1995],
["Emiliano Martínez", "Aston Villa", "Premier League", "Argentine", "🇦🇷", "CONMEBOL", "G", 1992],
["Youri Tielemans", "Man United", "Premier League", "Belgique", "🇧🇪", "UEFA", "M", 1997],
["Morgan Rogers", "Chelsea", "Premier League", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "M", 2004],
["Antoine Semenyo", "Man City", "Premier League", "Ghana", "🇬🇭", "CAF", "A", 2000],
["Jean-Philippe Mateta", "Crystal Palace", "Premier League", "France", "🇫🇷", "UEFA", "A", 1997],
["Adam Wharton", "Crystal Palace", "Premier League", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "M", 2004],
["Marc Guéhi", "Man City", "Premier League", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "D", 2000],
["Ismaïla Sarr", "Crystal Palace", "Premier League", "Sénégal", "🇸🇳", "CAF", "A", 1998],
["Jack Grealish", "Everton", "Premier League", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "M", 1995],
["Jordan Pickford", "Everton", "Premier League", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "G", 1994],
["Iliman Ndiaye", "Everton", "Premier League", "Sénégal", "🇸🇳", "CAF", "A", 2000],
["Alex Iwobi", "Fulham", "Premier League", "Nigéria", "🇳🇬", "CAF", "M", 1996],
["Timothy Castagne", "Fulham", "Premier League", "Belgique", "🇧🇪", "UEFA", "D", 1995],
["Chris Wood", "Nottingham Forest", "Premier League", "Nouvelle-Zélande", "🇳🇿", "OFC", "A", 1991],
["Morgan Gibbs-White", "Nottingham Forest", "Premier League", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "M", 2000],
["Matz Sels", "Nottingham Forest", "Premier League", "Belgique", "🇧🇪", "UEFA", "G", 1992],
["Kaoru Mitoma", "Brighton", "Premier League", "Japon", "🇯🇵", "AFC", "A", 1997],
["Granit Xhaka", "Sunderland", "Premier League", "Suisse", "🇨🇭", "UEFA", "M", 1992],
["Kylian Mbappé", "Real Madrid", "La Liga", "France", "🇫🇷", "UEFA", "A", 1998],
["Vinícius Júnior", "Real Madrid", "La Liga", "Brésil", "🇧🇷", "CONMEBOL", "A", 2000],
["Jude Bellingham", "Real Madrid", "La Liga", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "M", 2003],
["Federico Valverde", "Real Madrid", "La Liga", "Uruguay", "🇺🇾", "CONMEBOL", "M", 1998],
["Rodrygo", "Real Madrid", "La Liga", "Brésil", "🇧🇷", "CONMEBOL", "A", 2001],
["Thibaut Courtois", "Real Madrid", "La Liga", "Belgique", "🇧🇪", "UEFA", "G", 1992],
["Aurélien Tchouaméni", "Real Madrid", "La Liga", "France", "🇫🇷", "UEFA", "M", 2000],
["Eduardo Camavinga", "Real Madrid", "La Liga", "France", "🇫🇷", "UEFA", "M", 2002],
["Éder Militão", "Real Madrid", "La Liga", "Brésil", "🇧🇷", "CONMEBOL", "D", 1998],
["Antonio Rüdiger", "Real Madrid", "La Liga", "Allemagne", "🇩🇪", "UEFA", "D", 1993],
["Dean Huijsen", "Real Madrid", "La Liga", "Espagne", "🇪🇸", "UEFA", "D", 2005],
["Trent Alexander-Arnold", "Real Madrid", "La Liga", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "D", 1998],
["Franco Mastantuono", "Real Madrid", "La Liga", "Argentine", "🇦🇷", "CONMEBOL", "A", 2007],
["Arda Güler", "Real Madrid", "La Liga", "Turquie", "🇹🇷", "UEFA", "M", 2005],
["Lamine Yamal", "FC Barcelone", "La Liga", "Espagne", "🇪🇸", "UEFA", "A", 2007],
["Raphinha", "FC Barcelone", "La Liga", "Brésil", "🇧🇷", "CONMEBOL", "A", 1996],
["Robert Lewandowski", "Chicago Fire", "MLS", "Pologne", "🇵🇱", "UEFA", "A", 1988],
["Pedri", "FC Barcelone", "La Liga", "Espagne", "🇪🇸", "UEFA", "M", 2002],
["Gavi", "FC Barcelone", "La Liga", "Espagne", "🇪🇸", "UEFA", "M", 2004],
["Pau Cubarsí", "FC Barcelone", "La Liga", "Espagne", "🇪🇸", "UEFA", "D", 2007],
["Frenkie de Jong", "FC Barcelone", "La Liga", "Pays-Bas", "🇳🇱", "UEFA", "M", 1997],
["Ferran Torres", "PSG", "Ligue 1", "Espagne", "🇪🇸", "UEFA", "A", 2000],
["Marcus Rashford", "Man United", "Premier League", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "A", 1997],
["Marc-André ter Stegen", "FC Barcelone", "La Liga", "Allemagne", "🇩🇪", "UEFA", "G", 1992],
["Joan García", "FC Barcelone", "La Liga", "Espagne", "🇪🇸", "UEFA", "G", 2001],
["Fermín López", "FC Barcelone", "La Liga", "Espagne", "🇪🇸", "UEFA", "M", 2003],
["Dani Olmo", "FC Barcelone", "La Liga", "Espagne", "🇪🇸", "UEFA", "M", 1998],
["Antoine Griezmann", "Atlético Madrid", "La Liga", "France", "🇫🇷", "UEFA", "A", 1991],
["Julián Álvarez", "Atlético Madrid", "La Liga", "Argentine", "🇦🇷", "CONMEBOL", "A", 2000],
["Jan Oblak", "Atlético Madrid", "La Liga", "Slovénie", "🇸🇮", "UEFA", "G", 1993],
["Pablo Barrios", "Atlético Madrid", "La Liga", "Espagne", "🇪🇸", "UEFA", "M", 2001],
["Álex Baena", "Atlético Madrid", "La Liga", "Espagne", "🇪🇸", "UEFA", "M", 2001],
["Nico Williams", "Athletic Bilbao", "La Liga", "Espagne", "🇪🇸", "UEFA", "A", 2002],
["Iñaki Williams", "Athletic Bilbao", "La Liga", "Ghana", "🇬🇭", "CAF", "A", 1994],
["Unai Simón", "Athletic Bilbao", "La Liga", "Espagne", "🇪🇸", "UEFA", "G", 1997],
["Mikel Oyarzabal", "Real Sociedad", "La Liga", "Espagne", "🇪🇸", "UEFA", "A", 1997],
["Takefusa Kubo", "Real Sociedad", "La Liga", "Japon", "🇯🇵", "AFC", "A", 2001],
["Isco", "Real Betis", "La Liga", "Espagne", "🇪🇸", "UEFA", "M", 1992],
["Antony", "Real Betis", "La Liga", "Brésil", "🇧🇷", "CONMEBOL", "A", 2000],
["Kevin De Bruyne", "Naples", "Serie A", "Belgique", "🇧🇪", "UEFA", "M", 1991],
["Romelu Lukaku", "Naples", "Serie A", "Belgique", "🇧🇪", "UEFA", "A", 1993],
["Scott McTominay", "Naples", "Serie A", "Écosse", "🏴󠁧󠁢󠁳󠁣󠁴󠁿", "UEFA", "M", 1996],
["Rasmus Højlund", "Naples", "Serie A", "Danemark", "🇩🇰", "UEFA", "A", 2003],
["Lautaro Martínez", "Inter Milan", "Serie A", "Argentine", "🇦🇷", "CONMEBOL", "A", 1997],
["Nicolò Barella", "Inter Milan", "Serie A", "Italie", "🇮🇹", "UEFA", "M", 1997],
["Hakan Çalhanoğlu", "Inter Milan", "Serie A", "Turquie", "🇹🇷", "UEFA", "M", 1994],
["Alessandro Bastoni", "Inter Milan", "Serie A", "Italie", "🇮🇹", "UEFA", "D", 1999],
["Yann Sommer", "Inter Milan", "Serie A", "Suisse", "🇨🇭", "UEFA", "G", 1988],
["Marcus Thuram", "Inter Milan", "Serie A", "France", "🇫🇷", "UEFA", "A", 1997],
["Denzel Dumfries", "Inter Milan", "Serie A", "Pays-Bas", "🇳🇱", "UEFA", "D", 1996],
["Rafael Leão", "Galatasaray", "Süper Lig", "Portugal", "🇵🇹", "UEFA", "A", 1999],
["Christian Pulisic", "AC Milan", "Serie A", "États-Unis", "🇺🇸", "CONCACAF", "A", 1998],
["Mike Maignan", "AC Milan", "Serie A", "France", "🇫🇷", "UEFA", "G", 1995],
["Luka Modrić", "AC Milan", "Serie A", "Croatie", "🇭🇷", "UEFA", "M", 1985],
["Adrien Rabiot", "AC Milan", "Serie A", "France", "🇫🇷", "UEFA", "M", 1995],
["Christopher Nkunku", "AC Milan", "Serie A", "France", "🇫🇷", "UEFA", "A", 1997],
["Santiago Giménez", "AC Milan", "Serie A", "Mexique", "🇲🇽", "CONCACAF", "A", 2001],
["Alexis Saelemaekers", "AC Milan", "Serie A", "Belgique", "🇧🇪", "UEFA", "M", 1999],
["Ardon Jashari", "AC Milan", "Serie A", "Suisse", "🇨🇭", "UEFA", "M", 2002],
["Kenan Yıldız", "Juventus", "Serie A", "Turquie", "🇹🇷", "UEFA", "A", 2005],
["Dušan Vlahović", "Juventus", "Serie A", "Serbie", "🇷🇸", "UEFA", "A", 2000],
["Gleison Bremer", "Juventus", "Serie A", "Brésil", "🇧🇷", "CONMEBOL", "D", 1997],
["Michele Di Gregorio", "Juventus", "Serie A", "Italie", "🇮🇹", "UEFA", "G", 1997],
["Teun Koopmeiners", "Juventus", "Serie A", "Pays-Bas", "🇳🇱", "UEFA", "M", 1998],
["Jonathan David", "Juventus", "Serie A", "Canada", "🇨🇦", "CONCACAF", "A", 2000],
["Loïs Openda", "Juventus", "Serie A", "Belgique", "🇧🇪", "UEFA", "A", 2000],
["Paulo Dybala", "AS Roma", "Serie A", "Argentine", "🇦🇷", "CONMEBOL", "A", 1993],
["Mile Svilar", "AS Roma", "Serie A", "Serbie", "🇷🇸", "UEFA", "G", 1999],
["Lorenzo Pellegrini", "AS Roma", "Serie A", "Italie", "🇮🇹", "UEFA", "M", 1996],
["Ademola Lookman", "Atalanta", "Serie A", "Nigéria", "🇳🇬", "CAF", "A", 1997],
["Gianluca Scamacca", "Atalanta", "Serie A", "Italie", "🇮🇹", "UEFA", "A", 1999],
["Charles De Ketelaere", "Atalanta", "Serie A", "Belgique", "🇧🇪", "UEFA", "A", 2001],
["Mattia Zaccagni", "Lazio", "Serie A", "Italie", "🇮🇹", "UEFA", "A", 1995],
["Moise Kean", "Fiorentina", "Serie A", "Italie", "🇮🇹", "UEFA", "A", 2000],
["Domenico Berardi", "Sassuolo", "Serie A", "Italie", "🇮🇹", "UEFA", "A", 1994],
["Harry Kane", "Bayern Munich", "Bundesliga", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "A", 1993],
["Jamal Musiala", "Bayern Munich", "Bundesliga", "Allemagne", "🇩🇪", "UEFA", "M", 2003],
["Joshua Kimmich", "Bayern Munich", "Bundesliga", "Allemagne", "🇩🇪", "UEFA", "M", 1995],
["Manuel Neuer", "Bayern Munich", "Bundesliga", "Allemagne", "🇩🇪", "UEFA", "G", 1986],
["Michael Olise", "Bayern Munich", "Bundesliga", "France", "🇫🇷", "UEFA", "A", 2001],
["Dayot Upamecano", "Bayern Munich", "Bundesliga", "France", "🇫🇷", "UEFA", "D", 1998],
["Serge Gnabry", "Bayern Munich", "Bundesliga", "Allemagne", "🇩🇪", "UEFA", "A", 1995],
["Luis Díaz", "Bayern Munich", "Bundesliga", "Colombie", "🇨🇴", "CONMEBOL", "A", 1997],
["Jonathan Tah", "Bayern Munich", "Bundesliga", "Allemagne", "🇩🇪", "UEFA", "D", 1996],
["Serhou Guirassy", "Dortmund", "Bundesliga", "Guinée", "🇬🇳", "CAF", "A", 1996],
["Karim Adeyemi", "FC Barcelone", "La Liga", "Allemagne", "🇩🇪", "UEFA", "A", 2002],
["Nico Schlotterbeck", "Dortmund", "Bundesliga", "Allemagne", "🇩🇪", "UEFA", "D", 1999],
["Gregor Kobel", "Dortmund", "Bundesliga", "Suisse", "🇨🇭", "UEFA", "G", 1997],
["Julian Brandt", "Dortmund", "Bundesliga", "Allemagne", "🇩🇪", "UEFA", "M", 1996],
["Christoph Baumgartner", "RB Leipzig", "Bundesliga", "Autriche", "🇦🇹", "UEFA", "M", 1999],
["Arthur Vermeeren", "RB Leipzig", "Bundesliga", "Belgique", "🇧🇪", "UEFA", "M", 2005],
["Maarten Vandevoordt", "RB Leipzig", "Bundesliga", "Belgique", "🇧🇪", "UEFA", "G", 2002],
["Alejandro Grimaldo", "Leverkusen", "Bundesliga", "Espagne", "🇪🇸", "UEFA", "D", 1995],
["Patrik Schick", "Leverkusen", "Bundesliga", "Tchéquie", "🇨🇿", "UEFA", "A", 1996],
["Deniz Undav", "Stuttgart", "Bundesliga", "Allemagne", "🇩🇪", "UEFA", "A", 1996],
["Angelo Stiller", "Stuttgart", "Bundesliga", "Allemagne", "🇩🇪", "UEFA", "M", 2001],
["Arthur Theate", "Francfort", "Bundesliga", "Belgique", "🇧🇪", "UEFA", "D", 2000],
["Ousmane Dembélé", "PSG", "Ligue 1", "France", "🇫🇷", "UEFA", "A", 1997],
["Vitinha", "PSG", "Ligue 1", "Portugal", "🇵🇹", "UEFA", "M", 2000],
["Achraf Hakimi", "PSG", "Ligue 1", "Maroc", "🇲🇦", "CAF", "D", 1998],
["Marquinhos", "PSG", "Ligue 1", "Brésil", "🇧🇷", "CONMEBOL", "D", 1994],
["Nuno Mendes", "PSG", "Ligue 1", "Portugal", "🇵🇹", "UEFA", "D", 2002],
["João Neves", "PSG", "Ligue 1", "Portugal", "🇵🇹", "UEFA", "M", 2004],
["Fabián Ruiz", "PSG", "Ligue 1", "Espagne", "🇪🇸", "UEFA", "M", 1996],
["Khvicha Kvaratskhelia", "PSG", "Ligue 1", "Géorgie", "🇬🇪", "UEFA", "A", 2001],
["Bradley Barcola", "PSG", "Ligue 1", "France", "🇫🇷", "UEFA", "A", 2002],
["Désiré Doué", "PSG", "Ligue 1", "France", "🇫🇷", "UEFA", "A", 2005],
["Warren Zaïre-Emery", "PSG", "Ligue 1", "France", "🇫🇷", "UEFA", "M", 2006],
["Lucas Chevalier", "PSG", "Ligue 1", "France", "🇫🇷", "UEFA", "G", 2001],
["Illia Zabarnyi", "PSG", "Ligue 1", "Ukraine", "🇺🇦", "UEFA", "D", 2002],
["Gonçalo Ramos", "AC Milan", "Serie A", "Portugal", "🇵🇹", "UEFA", "A", 2001],
["Mason Greenwood", "Marseille", "Ligue 1", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "A", 2001],
["Pierre-Emerick Aubameyang", "Marseille", "Ligue 1", "Gabon", "🇬🇦", "CAF", "A", 1989],
["Gerónimo Rulli", "Marseille", "Ligue 1", "Argentine", "🇦🇷", "CONMEBOL", "G", 1992],
["Pierre-Emile Højbjerg", "Marseille", "Ligue 1", "Danemark", "🇩🇰", "UEFA", "M", 1995],
["Igor Paixão", "Marseille", "Ligue 1", "Brésil", "🇧🇷", "CONMEBOL", "A", 2000],
["Malick Fofana", "Lyon", "Ligue 1", "Belgique", "🇧🇪", "UEFA", "A", 2005],
["Olivier Giroud", "Lille", "Ligue 1", "France", "🇫🇷", "UEFA", "A", 1986],
["Maghnes Akliouche", "PSG", "Ligue 1", "France", "🇫🇷", "UEFA", "M", 2002],
["Folarin Balogun", "Monaco", "Ligue 1", "États-Unis", "🇺🇸", "CONCACAF", "A", 2001],
["Ansu Fati", "Monaco", "Ligue 1", "Espagne", "🇪🇸", "UEFA", "A", 2002],
["Cristiano Ronaldo", "Al-Nassr", "Saudi Pro League", "Portugal", "🇵🇹", "UEFA", "A", 1985],
["Karim Benzema", "Al-Ittihad", "Saudi Pro League", "France", "🇫🇷", "UEFA", "A", 1987],
["Sadio Mané", "Al-Nassr", "Saudi Pro League", "Sénégal", "🇸🇳", "CAF", "A", 1992],
["N'Golo Kanté", "Al-Ittihad", "Saudi Pro League", "France", "🇫🇷", "UEFA", "M", 1991],
["Riyad Mahrez", "Al-Ahli", "Saudi Pro League", "Algérie", "🇩🇿", "CAF", "A", 1991],
["Rúben Neves", "Al-Hilal", "Saudi Pro League", "Portugal", "🇵🇹", "UEFA", "M", 1997],
["Kalidou Koulibaly", "Al-Hilal", "Saudi Pro League", "Sénégal", "🇸🇳", "CAF", "D", 1991],
["Yassine Bounou", "Al-Hilal", "Saudi Pro League", "Maroc", "🇲🇦", "CAF", "G", 1991],
["Darwin Núñez", "Al-Hilal", "Saudi Pro League", "Uruguay", "🇺🇾", "CONMEBOL", "A", 1999],
["Theo Hernandez", "Al-Hilal", "Saudi Pro League", "France", "🇫🇷", "UEFA", "D", 1997],
["Marcelo Brozović", "Al-Nassr", "Saudi Pro League", "Croatie", "🇭🇷", "UEFA", "M", 1992],
["Sergej Milinković-Savić", "Al-Hilal", "Saudi Pro League", "Serbie", "🇷🇸", "UEFA", "M", 1995],
["Alexandre Lacazette", "NEOM SC", "Saudi Pro League", "France", "🇫🇷", "UEFA", "A", 1991],
["Ivan Toney", "Al-Ahli", "Saudi Pro League", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "A", 1996],
["Lionel Messi", "Inter Miami", "MLS", "Argentine", "🇦🇷", "CONMEBOL", "A", 1987],
["Luis Suárez", "Inter Miami", "MLS", "Uruguay", "🇺🇾", "CONMEBOL", "A", 1987],
["Rodrigo De Paul", "Inter Miami", "MLS", "Argentine", "🇦🇷", "CONMEBOL", "M", 1994],
["Son Heung-min", "Los Angeles FC", "MLS", "Corée du Sud", "🇰🇷", "AFC", "A", 1992],
["Thomas Müller", "Vancouver", "MLS", "Allemagne", "🇩🇪", "UEFA", "A", 1989],
["Hans Vanaken", "Club Bruges", "Pro League", "Belgique", "🇧🇪", "UEFA", "M", 1992],
["Christos Tzolis", "Leeds", "Premier League", "Grèce", "🇬🇷", "UEFA", "A", 2002],
["Simon Mignolet", "Club Bruges", "Pro League", "Belgique", "🇧🇪", "UEFA", "G", 1988],
["Vangelis Pavlidis", "Benfica", "Liga Portugal", "Grèce", "🇬🇷", "UEFA", "A", 1998],
["Nicolás Otamendi", "Benfica", "Liga Portugal", "Argentine", "🇦🇷", "CONMEBOL", "D", 1988],
["Anatoliy Trubin", "Benfica", "Liga Portugal", "Ukraine", "🇺🇦", "UEFA", "G", 2001],
["Dodi Lukébakio", "Benfica", "Liga Portugal", "Belgique", "🇧🇪", "UEFA", "A", 1997],
["Zeno Debast", "Sporting CP", "Liga Portugal", "Belgique", "🇧🇪", "UEFA", "D", 2003],
["Wout Weghorst", "Ajax", "Eredivisie", "Pays-Bas", "🇳🇱", "UEFA", "A", 1992],
["Guus Til", "PSV", "Eredivisie", "Pays-Bas", "🇳🇱", "UEFA", "M", 1997],
["Victor Osimhen", "Galatasaray", "Süper Lig", "Nigéria", "🇳🇬", "CAF", "A", 1998],
["Leroy Sané", "Galatasaray", "Süper Lig", "Allemagne", "🇩🇪", "UEFA", "A", 1996],
["İlkay Gündoğan", "Galatasaray", "Süper Lig", "Allemagne", "🇩🇪", "UEFA", "M", 1990],
["Lucas Torreira", "Galatasaray", "Süper Lig", "Uruguay", "🇺🇾", "CONMEBOL", "M", 1996],
["Ederson", "Fenerbahçe", "Süper Lig", "Brésil", "🇧🇷", "CONMEBOL", "G", 1993],
["Neymar", "Santos", "Brasileirão", "Brésil", "🇧🇷", "CONMEBOL", "A", 1992],
["Ángel Di María", "Rosario Central", "Primera División ARG", "Argentine", "🇦🇷", "CONMEBOL", "A", 1988],
["Yan Diomande", "Real Madrid", "La Liga", "Côte d'Ivoire", "🇨🇮", "CAF", "A", 2006],
["Elliot Anderson", "Man City", "Premier League", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "M", 2002],
["Ayyoub Bouaddi", "Man City", "Premier League", "Maroc", "🇲🇦", "CAF", "M", 2007],
["Carlos Baleba", "Man United", "Premier League", "Cameroun", "🇨🇲", "CAF", "M", 2004],
["Mateus Fernandes", "Tottenham", "Premier League", "Portugal", "🇵🇹", "UEFA", "M", 2004],
["Savinho", "Tottenham", "Premier League", "Brésil", "🇧🇷", "CONMEBOL", "A", 2004],
["Randal Kolo Muani", "Juventus", "Serie A", "France", "🇫🇷", "UEFA", "A", 1998],
["Jérémy Jacquet", "Liverpool", "Premier League", "France", "🇫🇷", "UEFA", "D", 2005],
["Curtis Jones", "Inter Milan", "Serie A", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "M", 2001],
["Andrey Santos", "Man United", "Premier League", "Brésil", "🇧🇷", "CONMEBOL", "M", 2004],
["Andy Robertson", "Tottenham", "Premier League", "Écosse", "🏴󠁧󠁢󠁳󠁣󠁴󠁿", "UEFA", "D", 1994],
["Nico Paz", "Côme", "Serie A", "Argentine", "🇦🇷", "CONMEBOL", "M", 2004],
["Ethan Nwaneri", "Arsenal", "Premier League", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "M", 2007],
["Myles Lewis-Skelly", "Arsenal", "Premier League", "Angleterre", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "UEFA", "D", 2006],
["Vanja Milinković-Savić", "Naples", "Serie A", "Serbie", "🇷🇸", "UEFA", "G", 1997],
["Rodrigo Mora", "FC Porto", "Liga Portugal", "Portugal", "🇵🇹", "UEFA", "M", 2007]
]/*JM-DATA-END*/;
